{{- range .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .name }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - image: scott829/graphgate-example-{{ .name }}:latest
          imagePullPolicy: Always
          name: {{ .name }}
          ports:
            - containerPort: 8000
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    graphgate.org/service: {{ .name }}
    graphgate.org/protocol: http
spec:
  ports:
    - name: http
      port: {{ .port }}
      targetPort: 8000
  selector:
    app: {{ .name }}
{{- end }}
