{{- range .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  annotations:
    rollme: {{ randAlphaNum 5 | quote }}
spec:
  replicas: {{ $.Values.replicas }}
  selector:
    matchLabels:
      app: {{ .name }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - image: scott829/graphgate-examples:latest
          imagePullPolicy: Always
          name: {{ .name }}
          ports:
            - containerPort: 8000
              name: http
          command:
            - {{ .name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    graphgate.org/service: {{ .name }}
spec:
  ports:
    - name: {{ .protocol }}
      port: 8000
      targetPort: {{ .port }}
  selector:
    app: {{ .name }}
{{- end }}
