---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: graphgate
automountServiceAccountToken: true
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: graphql-services-view
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: graphgate-binding
subjects:
  - kind: ServiceAccount
    name: graphgate
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: graphql-services-view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: graphgate-config
data:
  config.toml: {{ .Files.Get "config.toml" | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphgate
spec:
  replicas: {{ $.Values.gateway_replicas }}
  selector:
    matchLabels:
      app: graphgate
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: graphgate
    spec:
      serviceAccountName: graphgate
      volumes:
        - name: config-volume
          configMap:
            name: graphgate-config
      containers:
        - image: scott829/graphgate:latest
          imagePullPolicy: Always
          name: graphgate
          volumeMounts:
            - mountPath: /config
              name: config-volume
          args:
            - /config/config.toml
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: RUST_LOG
              value: graphgate=debug
---
apiVersion: v1
kind: Service
metadata:
  name: graphgate
spec:
  ports:
    - name: http
      port: 8000
      nodePort: 31000
      targetPort: {{ .Values.port }}
  selector:
    app: graphgate
  type: NodePort
