---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: graphgate
automountServiceAccountToken: true
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: graphql-services-view
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: graphgate-binding
subjects:
  - kind: ServiceAccount
    name: graphgate
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: graphql-services-view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphgate
  annotations:
    rollme: {{ randAlphaNum 5 | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphgate
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: graphgate
    spec:
      serviceAccountName: graphgate
      containers:
        - image: scott829/graphgate:latest
          imagePullPolicy: Always
          name: graphgate
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: RUST_LOG
              value: graphgate=trace
          args:
            - k8s
            - --bind
            - "0.0.0.0:{{ .Values.port }}"
---
apiVersion: v1
kind: Service
metadata:
  name: graphgate
spec:
  ports:
    - name: http
      port: 8000
      nodePort: 31000
      targetPort: {{ .Values.port }}
  selector:
    app: graphgate
  type: NodePort
