---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - image: jaegertracing/all-in-one:1.22
          imagePullPolicy: Always
          name: jaeger
          args:
            - 6831:6831/udp
            - 16686:16686
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-ui
spec:
  ports:
    - name: http
      port: 16686
      nodePort: 31001
      targetPort: 16686
  selector:
    app: graphgate
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
spec:
  ports:
    - name: http
      port: 6831
      targetPort: 6831
  selector:
    app: jaeger
