---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - image: jaegertracing/all-in-one:1.22.0
          name: jaeger
          env:
            - name: JAEGER_AGENT_PORT
              value: "6831"
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-ui
spec:
  ports:
    - name: http
      port: 16686
      nodePort: 31001
      targetPort: 16686
  selector:
    app: jaeger
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
spec:
  ports:
    - name: udp
      port: 6831
      protocol: UDP
      targetPort: 6831
  selector:
    app: jaeger
  clusterIP: None
