[package]
name = "graphgate"
version = "0.3.2"
authors = ["Sunli <scott_s829@163.com>"]
edition = "2018"

[dependencies]
graphgate-handler = { version = "0.3.1", path = "./crates/handler" }

serde = { version = "1.0.124", features = ["derive"] }
anyhow = "1.0.38"
structopt = "0.3.21"
kube = { version = "0.51.0", features = ["derive", "native-tls"], default-features = false }
k8s-openapi = { version = "0.11.0", features = ["v1_19"], default-features = false }
tokio = { version = "1.3.0", features = ["rt-multi-thread", "time", "macros", "sync", "signal"] }
warp = { version = "0.3.0", features = ["compression"] }
toml = "0.5.8"
tracing = "0.1.25"
tracing-subscriber = "0.2.17"
futures-util = "0.3.13"

[dev-dependencies]
async-graphql = { version = "2.5.14", default-features = false }
async-graphql-warp = "2.5.14"
fastrand = "1.4.0"
async-stream = "0.3.0"
futures-util = "0.3.13"

[workspace]
members = [
    "crates/schema",
    "crates/planner",
    "crates/validation",
    "crates/handler",
]
