[package]
name = "graphgate"
version = "0.3.0"
authors = ["Sunli <scott_s829@163.com>"]
edition = "2018"

[dependencies]
graphgate-core = { version = "0.3.0", path = "./crates/core" }

parser = { version = "2.5.9", package = "async-graphql-parser" }
value = { version = "2.5.9", package = "async-graphql-value" }
tokio = { version = "1.2.0", features = ["rt-multi-thread", "time", "macros", "sync"] }
warp = "0.3.0"
toml = "0.5.8"
serde = { version = "1.0.123", features = ["derive"] }
anyhow = "1.0.38"
futures-util = "0.3.13"
tracing = "0.1.25"
tracing-subscriber = "0.2.16"
serde_json = "1.0.64"
structopt = "0.3.21"
kube = { version = "0.51.0", features = ["derive", "native-tls"], default-features = false }
k8s-openapi = { version = "0.11.0", features = ["v1_19"], default-features = false }
schemars = { version = "0.8.0", features = ["chrono"] }
serde_yaml = "0.8.17"

[dev-dependencies]
async-graphql = { version = "2.5.12", default-features = false }
async-graphql-warp = "2.5.12"
fastrand = "1.4.0"
async-stream = "0.3.0"

[workspace]
members = [
    "crates/core",
]
