[package]
name = "federation-reviews"
version = "0.1.1"
authors = ["sunli <scott_s829@163.com>"]
edition = "2018"

[dependencies]
async-graphql = "2.5.10"
async-graphql-warp = "2.5.10"
tokio = { version = "1.0.2", features = ["macros", "rt-multi-thread"] }
warp = "0.3"