[package]
name = "graphgate-handler"
version = "0.3.2"
authors = ["Sunli <scott_s829@163.com>"]
edition = "2018"
description = "GraphGate is Apollo Federation implemented in Rust"
license = "MIT/Apache-2.0"
homepage = "https://github.com/async-graphql/graphgate"
repository = "https://github.com/async-graphql/graphgate"
keywords = ["gateway", "graphql", "federation"]

[dependencies]
graphgate-schema = { version = "0.3.1", path = "../schema" }
graphgate-planner = { version = "0.3.1", path = "../planner" }

warp = "0.3.0"
indexmap = { version = "1.6.2", features = ["serde-1"] }
futures-util = { version = "0.3.13", features = ["sink"] }
parser = { version = "2.5.9", package = "async-graphql-parser" }
value = { version = "2.5.9", package = "async-graphql-value" }
once_cell = "1.7.2"
tokio = { version = "1.3.0", features = ["net", "sync", "macros", "time"] }
tokio-stream = "0.1.4"
tokio-tungstenite = { version = "0.14.0", features = ["native-tls"] }
async-stream = "0.3.0"
spin = "0.7.1"
tracing = "0.1.25"
anyhow = "1.0.38"
http = "0.2.3"
serde = "1.0.124"
serde_json = "1.0.64"
reqwest = { version = "0.11.2", default-features = false, features = ["native-tls", "gzip", "brotli", "json"] }
async-trait = "0.1.48"
opentelemetry = "0.12.0"
chrono = { version = "0.4.19", features = ["serde"] }
