[package]
name = "graphgate-validation"
version = "0.3.2"
authors = ["Sunli <scott_s829@163.com>"]
edition = "2018"

[dependencies]
graphgate-schema = { version = "0.3.1", path = "../schema" }

parser = { version = "2.5.9", package = "async-graphql-parser" }
value = { version = "2.5.9", package = "async-graphql-value" }
indexmap = { version = "1.6.2", features = ["serde-1"] }

[dev-dependencies]
once_cell = "1.7.2"
