[package]
name = "graphgate-planner"
version = "0.3.1"
authors = ["Sunli <scott_s829@163.com>"]
edition = "2018"

[dependencies]
graphgate-schema = { version = "0.3.1", path = "../schema" }
graphgate-validation = { version = "0.3.1", path = "../validation" }

parser = { version = "2.5.9", package = "async-graphql-parser" }
value = { version = "2.5.9", package = "async-graphql-value" }
indexmap = { version = "1.6.2", features = ["serde-1"] }
serde = "1.0.124"

[dev-dependencies]
globset = "0.4.6"
serde_json = "1.0.64"
