name: Release

on:
  push:
    branches:
      - release

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get version
        run: echo PACKAGE_VERSION=$(sed -nE 's/^\s*version = "(.*?)"/\1/p' Cargo.toml) >> $GITHUB_ENV
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: |
            scott829/graphgate:${{ env.PACKAGE_VERSION }}
            scott829/graphgate:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  examples-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - name: accounts
          - name: products
          - name: reviews
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push ${{ matrix.package.name }}
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./examples
          file: Dockerfile-${{ matrix.package.name }}
          tags: scott829/graphgate-example-${{ matrix.package.name }}:latest
      - name: Kubernetes toolset installer
        uses: yokawasa/action-setup-kube-tools@v0.2.0
      - name: Deployment
        run: |
          mkdir ~/.kube
          cat ${{ secrets.K8S_CONFIG }} > ~/.kube/config
          cd examples
          helm upgrade -i -n graphgate graphgate .
          