name: Release

on:
  push:
    branches:
      - release

jobs:
  graphgate-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get version
        run: echo PACKAGE_VERSION=$(sed -nE 's/^\s*version = "(.*?)"/\1/p' Cargo.toml) >> $GITHUB_ENV
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: |
            scott829/graphgate:${{ env.PACKAGE_VERSION }}
            scott829/graphgate:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  examples-docker:
    runs-on: ubuntu-latest
    needs: graphgate-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push ${{ matrix.package.name }}
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile-examples
          tags: scott829/graphgate-examples:latest
      - name: Deploy to Kubernetes
        uses: WyriHaximus/github-action-helm3@v2
        with:
          kubeconfig: '${{ secrets.K8S_CONFIG }}'
          exec: |
            helm uninstall -n graphgate graphgate
            helm upgrade --create-namespace -i -n graphgate graphgate examples/helm
